services:
  postgres:
    image: postgres:16
    container_name: webshop_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: webshop
      POSTGRES_PASSWORD: webshop123
      POSTGRES_DB: webshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: